# Generated by Django 5.1.2 on 2025-03-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0020_historicalhotel_historicallocalguide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iban', models.CharField(max_length=34, unique=True, verbose_name='IBAN')),
                ('swift', models.CharField(max_length=11, verbose_name='SWIFT/BIC Code')),
                ('beneficiary', models.CharField(max_length=255, verbose_name='Beneficiary Name')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code (CP)')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_location', to='services.location')),
            ],
            options={
                'verbose_name': 'Bank Accounts',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['beneficiary'],
            },
        ),
    ]
