# Generated by Django 5.1.2 on 2025-04-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccounts',
            options={'ordering': ['beneficiary'], 'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
    ]
