# Generated by Django 5.1.2 on 2024-12-03 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_remove_proposalsectionitem_content_type_and_more'),
        ('services', '0003_rename_bus_price_airport_transfers_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax', models.PositiveIntegerField()),
                ('variable_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fixed_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_cost_per_person', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=5)),
                ('margin', models.PositiveIntegerField(default=10)),
                ('currency', models.ForeignKey(default='EUR', on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='services.currency')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='proposals.proposal')),
            ],
        ),
    ]
