# Generated by Django 5.1.2 on 2024-12-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposalbudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalbudget',
            name='currency',
        ),
    ]
