# Generated by Django 5.1.2 on 2024-12-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_remove_proposalbudget_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsectionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposalsectionitem',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposalsectionitem',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='item_service', to='proposals.servicelink'),
        ),
    ]
