# Generated by Django 5.1.2 on 2024-12-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_proposalsectionitem_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalsectionitem',
            name='services',
        ),
        migrations.AddField(
            model_name='proposalsectionitem',
            name='service_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposalsectionitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='ServiceLink',
        ),
    ]
