# Generated by Django 5.1.2 on 2024-12-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_proposal_request_alter_proposal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='request',
            new_name='trip_request',
        ),
    ]
