# Generated by Django 5.1.2 on 2024-12-11 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_rename_request_proposal_trip_request'),
        ('requests', '0012_alter_triprequests_city_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='trip_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_proposal', to='requests.triprequests'),
        ),
    ]
