# Generated by Django 5.1.2 on 2025-02-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_proposalbudget_courtesy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalbudget',
            old_name='courtesy',
            new_name='free_of_charge',
        ),
        migrations.RenameField(
            model_name='proposalbudget',
            old_name='courtesy_amount',
            new_name='free_of_charge_amount',
        ),
    ]
