# Generated by Django 5.1.2 on 2025-02-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_rename_courtesy_proposalbudget_free_of_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalbudget',
            name='free_of_charge',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
