# Generated by Django 5.1.2 on 2025-03-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0019_alter_proposalsectionitem_city'),
        ('services', '0018_rename_city_location_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalsectionitem',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item_city', to='services.location'),
        ),
    ]
