# Generated by Django 5.1.2 on 2025-03-09 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0020_alter_proposalsectionitem_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalbudget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalbudget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proposalsectionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalsectionitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
