# Generated by Django 5.1.2 on 2025-03-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0022_historicalproposal_historicalproposalbudget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproposal',
            old_name='is_draft',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='is_draft',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='internal_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='status',
            field=models.CharField(choices=[('', 'Select an option'), ('Not finished', 'Not finished'), ('Send to client', 'Send to client'), ('Ready for review', 'Ready for review')], default='Not finished', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='internal_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('', 'Select an option'), ('Not finished', 'Not finished'), ('Send to client', 'Send to client'), ('Ready for review', 'Ready for review')], default='Not finished', max_length=50),
            preserve_default=False,
        ),
    ]
