# Generated by Django 5.1.2 on 2025-03-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0023_rename_is_draft_historicalproposal_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproposalsectionitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposalsectionitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
