# Generated by Django 5.1.2 on 2025-03-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0024_historicalproposalsectionitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposal',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='status',
            field=models.CharField(choices=[('', 'Select an option'), ('Not finished', 'Not finished'), ('Ready for review', 'Ready for review'), ('Send to client', 'Send to client')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalproposalbudget',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposalsectionitem',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposalsectionitem',
            name='section_name',
            field=models.CharField(choices=[('Accommodations', 'Accommodations'), ('Public Transport', 'Public Transport'), ('Private Transport', 'Private Transport'), ('Transfers', 'Transfers'), ('Activity', 'Activity'), ('Local Guides', 'Local Guides'), ('Tour Leader', 'Tour Leader'), ('Other Services - Variable', 'Other Services - Variable'), ('Other Services - Fixed', 'Other Services - Fixed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('', 'Select an option'), ('Not finished', 'Not finished'), ('Ready for review', 'Ready for review'), ('Send to client', 'Send to client')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proposalsectionitem',
            name='section_name',
            field=models.CharField(choices=[('Accommodations', 'Accommodations'), ('Public Transport', 'Public Transport'), ('Private Transport', 'Private Transport'), ('Transfers', 'Transfers'), ('Activity', 'Activity'), ('Local Guides', 'Local Guides'), ('Tour Leader', 'Tour Leader'), ('Other Services - Variable', 'Other Services - Variable'), ('Other Services - Fixed', 'Other Services - Fixed')], max_length=50),
        ),
    ]
