# Generated by Django 5.1.2 on 2025-04-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0025_alter_historicalproposal_history_change_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposal',
            name='status',
            field=models.CharField(choices=[('', 'Select an option'), ('Not finished', 'Not finished'), ('Ready for review', 'Ready for review'), ('Send to client', 'Send to client'), ('Approved by client', 'Approved by client'), ('Rejected by client', 'Rejected by client')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalproposalsectionitem',
            name='section_name',
            field=models.CharField(choices=[('Accommodations', 'Accommodations'), ('Public Transport', 'Public Transport'), ('Private Transport', 'Private Transport'), ('Transfers', 'Transfers'), ('Activity', 'Activity'), ('Local Guides', 'Local Guides'), ('Tour Leader', 'Tour Leader'), ('Meals', 'Meals'), ('Other Services - Variable', 'Other Services - Variable'), ('Other Services - Fixed', 'Other Services - Fixed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('', 'Select an option'), ('Not finished', 'Not finished'), ('Ready for review', 'Ready for review'), ('Send to client', 'Send to client'), ('Approved by client', 'Approved by client'), ('Rejected by client', 'Rejected by client')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proposalsectionitem',
            name='section_name',
            field=models.CharField(choices=[('Accommodations', 'Accommodations'), ('Public Transport', 'Public Transport'), ('Private Transport', 'Private Transport'), ('Transfers', 'Transfers'), ('Activity', 'Activity'), ('Local Guides', 'Local Guides'), ('Tour Leader', 'Tour Leader'), ('Meals', 'Meals'), ('Other Services - Variable', 'Other Services - Variable'), ('Other Services - Fixed', 'Other Services - Fixed')], max_length=50),
        ),
    ]
