# Generated by Django 5.1.2 on 2025-02-17 19:14

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='providers',
            name='email',
            field=models.EmailField(default='a@2.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='providers',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+34788940032', help_text='Enter phone number in international format. Example: +123456789', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
