# Generated by Django 5.1.2 on 2025-03-05 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_alter_providers_city'),
        ('services', '0018_rename_city_location_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='provider_city', to='services.location'),
        ),
    ]
