# Generated by Django 5.1.2 on 2025-04-14 09:30

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_alter_providers_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'Select an option'), ('transfers', 'Transfers'), ('activity', 'Activity'), ('accommodation', 'Accommodation'), ('food and beverage', 'Food & Beverage'), ('local guides', 'Local guides'), ('tour leaders', 'Tour leaders'), ('public transport', 'Public Transport'), ('private transport', 'Private Transport'), ('other', 'Other')], help_text='Select a service', max_length=100),
        ),
    ]
