# Generated by Django 5.1.2 on 2024-11-05 14:08

import voya.companies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(upload_to='company_logos/', validators=[voya.companies.validators.FileSizeValidator(5)]),
        ),
    ]
