# Generated by Django 5.1.2 on 2024-12-02 17:28

import cloudinary.models
import voya.companies.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_companyprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[voya.companies.validators.FileSizeValidator(5)], verbose_name='company_logos'),
        ),
    ]
