# Generated by Django 5.1.2 on 2024-12-02 18:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_companyprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='company_logos'),
        ),
    ]
