# Generated by Django 5.1.2 on 2024-11-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='label',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='title',
            field=models.CharField(choices=[('title', 'Select your title'), ('miss', 'Miss'), ('mrs', 'Mrs'), ('mr', 'Mr')], max_length=10),
        ),
    ]
