# Generated by Django 5.1.2 on 2025-04-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeeprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('pt', 'Portuguese')], default='en', max_length=10),
        ),
    ]
