# Generated by Django 5.1.2 on 2024-11-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_currency_currency_currency_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfers',
            old_name='bus_price_airport',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='bus_price_city',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='car_price_airport',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='car_price_city',
        ),
        migrations.AddField(
            model_name='transfers',
            name='transfer_name',
            field=models.CharField(default='Car around the city', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfers',
            name='type',
            field=models.CharField(choices=[('City car', 'Car around the city'), ('Airport car', 'Car to the airport'), ('City bus', 'Bus around the city'), ('Airport bus', 'Bus to the airport')], default='City car', max_length=50),
            preserve_default=False,
        ),
    ]
