# Generated by Django 5.1.2 on 2025-02-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_currency_currency_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_from',
            field=models.CharField(choices=[('', 'Select an option'), ('eur', 'EUR'), ('usd', 'USD'), ('mxn', 'MXN'), ('chf', 'CHF')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('', 'Select an option'), ('2 star hotel', '2 Stars hotel'), ('3 star hotel', '3 Stars hotel'), ('4 star hotel', '4 Stars hotel'), ('5 star hotel', '5 Stars hotel'), ('hostel private bathroom', 'Hostel with private bathroom'), ('apartment', 'Apartment'), ('camping', 'Camping')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='privatetransport',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatetransport',
            name='type',
            field=models.CharField(choices=[('', 'Select an option'), ('private bus', 'Private bus'), ('private car', 'Private car'), ('private van', 'Private van'), ('private boat', 'Private boat'), ('luxury car (4pax)', 'Luxury car (4 pax)'), ('luxury van (7pax)', 'Luxury van (7 pax)'), ('luxury bus (8+pax)', 'Luxury bus (8+ pax)'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='publictransport',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publictransport',
            name='type',
            field=models.CharField(choices=[('', 'Select an option'), ('public bus', 'Public Bus'), ('train', 'Train'), ('flights', 'Flights'), ('ferry', 'Ferry'), ('metro', 'Metro'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='price_includes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tour_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='type',
            field=models.CharField(choices=[('', 'Select an option'), ('City car', 'Car around the city'), ('Airport car', 'Car to the airport'), ('City bus', 'Bus around the city'), ('Airport bus', 'Bus to the airport'), ('private boat', 'Private boat'), ('luxury car (4pax)', 'Luxury car (4 pax)'), ('luxury van (7pax)', 'Luxury van (7 pax)'), ('luxury bus (8+pax)', 'Luxury bus (8+ pax)')], default='', max_length=50),
        ),
    ]
