# Generated by Django 5.1.2 on 2025-02-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_currency_currency_from_alter_hotel_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localguide',
            old_name='guide_name',
            new_name='name',
        ),
    ]
