# Generated by Django 5.1.2 on 2025-02-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_hotel_provider_localguide_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='localguide',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='privatetransport',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='publictransport',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='provider',
        ),
    ]
