# Generated by Django 5.1.2 on 2025-03-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_hotel_city_alter_localguide_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_city', to='services.location'),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_city', to='services.location'),
        ),
        migrations.AlterField(
            model_name='privatetransport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_city', to='services.location'),
        ),
        migrations.AlterField(
            model_name='publictransport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_city', to='services.location'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_city', to='services.location'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_city', to='services.location'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_city', to='services.location'),
        ),
    ]
