# Generated by Django 5.1.2 on 2025-03-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_hotel_city_alter_localguide_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='city',
            new_name='city_name',
        ),
    ]
