# Generated by Django 5.1.2 on 2025-03-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_alter_historicalhotel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_from',
            field=models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD'), ('mxn', 'MXN'), ('chf', 'CHF')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_to',
            field=models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD'), ('mxn', 'MXN'), ('chf', 'CHF')], default='eur', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcurrency',
            name='currency_from',
            field=models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD'), ('mxn', 'MXN'), ('chf', 'CHF')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcurrency',
            name='currency_to',
            field=models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD'), ('mxn', 'MXN'), ('chf', 'CHF')], default='eur', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalhotel',
            name='category',
            field=models.CharField(choices=[('2 Stars hotel', '2 Stars hotel'), ('3 Stars hotel', '3 Stars hotel'), ('4 Stars hotel', '4 Stars hotel'), ('5 Stars hotel', '5 Stars hotel'), ('Hostel private bathroom', 'Hostel with private bathroom'), ('Apartment', 'Apartment'), ('Camping', 'Camping')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalprivatetransport',
            name='type',
            field=models.CharField(choices=[('Private bus', 'Private bus'), ('Private car', 'Private car'), ('Private van', 'Private van'), ('Private boat', 'Private boat'), ('Luxury car (4pax)', 'Luxury car (4 pax)'), ('Luxury van (7pax)', 'Luxury van (7 pax)'), ('Luxury bus (8+pax)', 'Luxury bus (8+ pax)'), ('Check point', 'Check point'), ('Driver accommodation', 'Driver accommodation'), ('Driver meals', 'Driver meals'), ('Motorways and parkings', 'Motorways and parkings'), ('Other', 'Other')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalpublictransport',
            name='type',
            field=models.CharField(choices=[('Public bus', 'Public bus'), ('Train', 'Train'), ('Flights', 'Flights'), ('Ferry', 'Ferry'), ('Metro', 'Metro'), ('Other', 'Other')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='type',
            field=models.CharField(choices=[('Ticket', 'Ticket'), ('Pack', 'Package'), ('Other', 'Other')], default='choice', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('2 Stars hotel', '2 Stars hotel'), ('3 Stars hotel', '3 Stars hotel'), ('4 Stars hotel', '4 Stars hotel'), ('5 Stars hotel', '5 Stars hotel'), ('Hostel private bathroom', 'Hostel with private bathroom'), ('Apartment', 'Apartment'), ('Camping', 'Camping')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='privatetransport',
            name='type',
            field=models.CharField(choices=[('Private bus', 'Private bus'), ('Private car', 'Private car'), ('Private van', 'Private van'), ('Private boat', 'Private boat'), ('Luxury car (4pax)', 'Luxury car (4 pax)'), ('Luxury van (7pax)', 'Luxury van (7 pax)'), ('Luxury bus (8+pax)', 'Luxury bus (8+ pax)'), ('Check point', 'Check point'), ('Driver accommodation', 'Driver accommodation'), ('Driver meals', 'Driver meals'), ('Motorways and parkings', 'Motorways and parkings'), ('Other', 'Other')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='publictransport',
            name='type',
            field=models.CharField(choices=[('Public bus', 'Public bus'), ('Train', 'Train'), ('Flights', 'Flights'), ('Ferry', 'Ferry'), ('Metro', 'Metro'), ('Other', 'Other')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Ticket', 'Ticket'), ('Pack', 'Package'), ('Other', 'Other')], default='choice', max_length=20),
        ),
    ]
