# Generated by Django 5.1.2 on 2026-03-11 13:35

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_alter_historicalhotel_country_and_more'),
    ]
operations = [

]
