# Generated by Django 5.1.2 on 2024-11-04 10:46

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(choices=[('mr', 'Mr.'), ('miss', 'Miss'), ('mrs', 'Mrs')], max_length=10)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('job_title', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number in international format. Example: +123456789', max_length=128, region=None)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='companies.companyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
