# Generated by Django 5.1.2 on 2024-11-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_clientprofile_label_clientprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='title',
            field=models.CharField(choices=[('title', 'Select your title'), ('miss', 'Miss'), ('mrs', 'Mrs'), ('mr', 'Mr')], max_length=10),
        ),
    ]
