# Generated by Django 5.1.2 on 2024-11-10 21:07

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_origin', django_countries.fields.CountryField(max_length=2)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('country_destinations', django_countries.fields.CountryField(max_length=2)),
                ('city_destinations', models.CharField(choices=[('Amsterdam', 'Amsterdam'), ('Athens', 'Athens'), ('Barcelona', 'Barcelona'), ('Belgrade', 'Belgrade'), ('Berlin', 'Berlin'), ('Bruges', 'Bruges'), ('Brussels', 'Brussels'), ('Budapest', 'Budapest'), ('Copenhagen', 'Copenhagen'), ('Dublin', 'Dublin'), ('Edinburgh', 'Edinburgh'), ('Florence', 'Florence'), ('Geneva', 'Geneva'), ('Helsinki', 'Helsinki'), ('Istanbul', 'Istanbul'), ('Lisbon', 'Lisbon'), ('London', 'London'), ('Lucerne', 'Lucerne'), ('Madrid', 'Madrid'), ('Milan', 'Milan'), ('Moscow', 'Moscow'), ('Munich', 'Munich'), ('Naples', 'Naples'), ('Nice', 'Nice'), ('Oslo', 'Oslo'), ('Paris', 'Paris'), ('Prague', 'Prague'), ('Pisa', 'Pisa'), ('Reykjavik', 'Reykjavik'), ('Rome', 'Rome'), ('Salzburg', 'Salzburg'), ('Santorini', 'Santorini'), ('Seville', 'Seville'), ('Sofia', 'Sofia'), ('Split', 'Split'), ('Stockholm', 'Stockholm'), ('Varna', 'Varna'), ('Venice', 'Venice'), ('Vienna', 'Vienna'), ('Warsaw', 'Warsaw'), ('Zagreb', 'Zagreb'), ('Zurich', 'Zurich')], max_length=50)),
                ('other_destinations', models.CharField(max_length=100)),
                ('budget', models.PositiveIntegerField()),
                ('trip_duration', models.IntegerField()),
                ('trip_start_date', models.DateField()),
                ('trip_end_date', models.DateField()),
                ('age_range', models.IntegerField()),
                ('min_participants', models.PositiveIntegerField()),
                ('max_participants', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD'), ('mxn', 'MXN'), ('chf', 'CHF')], max_length=10)),
                ('transportation_type', models.CharField(choices=[('no transportation', "No transportation - I'll take care of it"), ('private bus', 'Private Bus'), ('public buses', 'Public Buses'), ('trains', 'Trains'), ('flights', 'Flights'), ('taxi', 'Taxi'), ('airport/station transfers', 'Airport/Station Transfers')], max_length=100)),
                ('transportation_details', models.TextField()),
                ('accommodations', models.CharField(choices=[('none', "None -  I'll take care of it"), ('2-3 star hotels', '2-3 Star Hotels'), ('4-5 star hotels', '4-5 Star Hotels'), ('hostels with private bathroom', 'Hostels with private bathroom'), ('apartment', 'Apartment'), ('camping', 'Camping')], max_length=100)),
                ('accommodations_details', models.TextField()),
                ('meals', models.CharField(choices=[('no meals included', 'No meals included'), ('breakfast only (BB)', 'Breakfast Only (BB)'), ('breakfast & dinner (HB)', 'Breakfast & Dinner (HB)'), ('breakfast, lunch & dinner (FB)', 'Breakfast, Lunch & Dinner (FB)')], max_length=50)),
                ('meals_details', models.TextField()),
                ('staff', models.CharField(choices=[('Tour leader during the entire trip', 'Tour leader during the entire trip'), ('Official tourist guides in each city', 'Official Tourist Guides')], max_length=50)),
                ('kind_of_group', models.CharField(choices=[('cultural_sightseeing', 'Cultural Group - Sightseeing'), ('schools_youth', 'Schools, Students or Youth'), ('backpackers', 'Backpackers'), ('theme_parks', 'Theme Parks (Eurodisney, Pinocchio, Mirabilandia, Puerto Aventura, Harry Potter...)'), ('study_language', 'Study or Language Package'), ('festivals_events', 'Festivals or Events'), ('sport', 'Sport'), ('family', 'Family'), ('religious', 'Religious'), ('relax_health_spas', 'Relax, Health, and SPAs'), ('adventure_nature', 'Adventure, Nature, Eco-tourism'), ('foodies_gastro_wine', 'Foodies - Gastro Tours - Wine Tours'), ('shopping', 'Shopping Tours'), ('yoga_meditation', 'Yoga or Meditation'), ('theme_tour', 'Theme Tour (Urban Art, Architecture, Science, Cinema...)'), ('photo_tours', 'Photo Tours'), ('cruises', 'Cruises')], max_length=100)),
                ('type_of_trip', models.TextField()),
                ('additional_observations', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
