# Generated by Django 5.1.2 on 2024-11-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_triprequests_created_by_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequests',
            name='title',
            field=models.CharField(default=0.0004938271604938272, max_length=100),
            preserve_default=False,
        ),
    ]
