# Generated by Django 5.1.2 on 2024-11-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_triprequests_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequests',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
