# Generated by Django 5.1.2 on 2024-11-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_remove_triprequests_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequests',
            name='currency',
            field=models.CharField(choices=[('currency', 'Choose currency'), ('eur', 'EUR'), ('usd', 'USD'), ('mxn', 'MXN'), ('chf', 'CHF')], max_length=20),
        ),
    ]
