# Generated by Django 5.1.2 on 2024-11-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_alter_triprequests_country_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequests',
            name='other_destinations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
