# Generated by Django 5.1.2 on 2025-01-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0013_alter_triprequests_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequests',
            name='accommodations',
            field=models.CharField(choices=[('acc', 'Select accommodations type'), ('none', "None -  I'll take care of it"), ('2-3 star hotels', '2-3 Star Hotels'), ('4-5 star hotels', '4-5 Star Hotels'), ('hostels with private bathroom', 'Hostels with private bathroom'), ('apartment', 'Apartment'), ('camping', 'Camping')], default='acc', max_length=100),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='accommodations_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='additional_observations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='currency',
            field=models.CharField(choices=[('currency', 'Select currency'), ('eur', 'EUR'), ('usd', 'USD'), ('mxn', 'MXN'), ('chf', 'CHF')], default='currency', max_length=20),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='kind_of_group',
            field=models.CharField(blank=True, choices=[('group', 'Select type of group'), ('cultural_sightseeing', 'Cultural Group - Sightseeing'), ('schools_youth', 'Schools, Students or Youth'), ('backpackers', 'Backpackers'), ('theme_parks', 'Theme Parks (Eurodisney, Pinocchio, Mirabilandia, Puerto Aventura, Harry Potter...)'), ('study_language', 'Study or Language Package'), ('festivals_events', 'Festivals or Events'), ('sport', 'Sport'), ('family', 'Family'), ('religious', 'Religious'), ('relax_health_spas', 'Relax, Health, and SPAs'), ('adventure_nature', 'Adventure, Nature, Eco-tourism'), ('foodies_gastro_wine', 'Foodies - Gastro Tours - Wine Tours'), ('shopping', 'Shopping Tours'), ('yoga_meditation', 'Yoga or Meditation'), ('theme_tour', 'Theme Tour (Urban Art, Architecture, Science, Cinema...)'), ('photo_tours', 'Photo Tours'), ('cruises', 'Cruises')], default='group', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='meals',
            field=models.CharField(blank=True, choices=[('meal', 'Select meals service'), ('no meals included', 'No meals included'), ('breakfast only (BB)', 'Breakfast Only (BB)'), ('breakfast & dinner (HB)', 'Breakfast & Dinner (HB)'), ('breakfast, lunch & dinner (FB)', 'Breakfast, Lunch & Dinner (FB)')], default='meal', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='meals_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='staff',
            field=models.CharField(blank=True, choices=[('staff', 'Select staff service'), ('Tour leader during the entire trip', 'Tour leader during the entire trip'), ('Official tourist guides in each city', 'Official Tourist Guides')], default='staff', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='transportation_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='transportation_type',
            field=models.CharField(choices=[('transport', 'Select transportation type'), ('no transportation', "No transportation - I'll take care of it"), ('private bus', 'Private Bus'), ('public buses', 'Public Buses'), ('trains', 'Trains'), ('flights', 'Flights'), ('taxi', 'Taxi'), ('airport/station transfers', 'Airport/Station Transfers')], default='transport', max_length=100),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='type_of_trip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
