# Generated by Django 5.1.2 on 2025-03-05 15:03

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0020_alter_triprequests_country_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequests',
            name='city_destinations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'Select a city'), ('Generic', 'Generic city'), ('-', '-'), ('Amsterdam', 'Amsterdam'), ('Athens', 'Athens'), ('Ávila', 'Ávila'), ('Barcelona', 'Barcelona'), ('Belgrade', 'Belgrade'), ('Berlin', 'Berlin'), ('Bologna', 'Bologna'), ('Bordeaux', 'Bordeaux'), ('Bourges', 'Bourges'), ('Bruges', 'Bruges'), ('Brussels', 'Brussels'), ('Budapest', 'Budapest'), ('Cappadocia', 'Cappadocia'), ('Capri', 'Capri'), ('Chamonix', 'Chamonix'), ('Cinque Terre', 'Cinque Terre'), ('Coira/Chur', 'Coira/Chur'), ('Colmar', 'Colmar'), ('Como', 'Como'), ('Copenhagen', 'Copenhagen'), ('Cracow', 'Cracow'), ('Dublin', 'Dublin'), ('Dubrovnik', 'Dubrovnik'), ('Edinburgh', 'Edinburgh'), ('Fátima', 'Fátima'), ('Florence', 'Florence'), ('Frankfurt', 'Frankfurt'), ('Garbagnate Milanese', 'Garbagnate Milanese'), ('Geneva', 'Geneva'), ('Ghent', 'Ghent'), ('Glasgow', 'Glasgow'), ('Gothenburg', 'Gothenburg'), ('Harrogate', 'Harrogate'), ('Helsinki', 'Helsinki'), ('Highlands', 'Highlands'), ('Hvar', 'Hvar'), ('Ibiza', 'Ibiza'), ('Istanbul', 'Istanbul'), ('Lisbon', 'Lisbon'), ('Lisieux', 'Lisieux'), ('Liverpool', 'Liverpool'), ('Loire', 'Loire'), ('London', 'London'), ('Lourdes', 'Lourdes'), ('Lucerne', 'Lucerne'), ('Lyon', 'Lyon'), ('Madrid', 'Madrid'), ('Milan', 'Milan'), ('Montecatini Terme', 'Montecatini Terme'), ('Montserrat', 'Montserrat'), ('Moscow', 'Moscow'), ('Munich', 'Munich'), ('Mykonos', 'Mykonos'), ('Naples', 'Naples'), ('Nuremberg', 'Nuremberg'), ('Nice', 'Nice'), ('Oporto', 'Oporto'), ('Oslo', 'Oslo'), ('Pamplona', 'Pamplona'), ('Paris', 'Paris'), ('Prague', 'Prague'), ('Pisa', 'Pisa'), ('Reykjavik', 'Reykjavik'), ('Rome', 'Rome'), ('Salzburg', 'Salzburg'), ('Santiago de Compostela', 'Santiago de Compostela'), ('Santorini', 'Santorini'), ('Seville', 'Seville'), ('Sofia', 'Sofia'), ('Split', 'Split'), ('Stockholm', 'Stockholm'), ('Varna', 'Varna'), ('Venice', 'Venice'), ('Vienna', 'Vienna'), ('Vinci', 'Vinci'), ('Warsaw', 'Warsaw'), ('Zagreb', 'Zagreb'), ('Zaragoza', 'Zaragoza'), ('Zurich', 'Zurich')], max_length=670),
        ),
    ]
