# Generated by Django 5.1.2 on 2025-03-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0023_historicaltriprequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='accommodations',
            field=models.CharField(choices=[('acc', 'Select accommodations type'), ('2-3 star hotels', '2-3 Star Hotels'), ('4-5 star hotels', '4-5 Star Hotels'), ('hostels with private bathroom', 'Hostels with private bathroom'), ('apartment', 'Apartment'), ('camping', 'Camping'), ('none', "None -  I'll take care of it"), ('other', 'Other')], default='acc', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='meals',
            field=models.CharField(blank=True, choices=[('meal', 'Select meals service'), ('breakfast only (BB)', 'Breakfast Only (BB)'), ('breakfast & dinner (HB)', 'Breakfast & Dinner (HB)'), ('breakfast, lunch & dinner (FB)', 'Breakfast, Lunch & Dinner (FB)'), ('no meals included', 'No meals included'), ('other', 'Other')], default='meal', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='staff',
            field=models.CharField(blank=True, choices=[('staff', 'Select staff service'), ('Tour leader during the entire trip', 'Tour leader during the entire trip'), ('Official tourist guides in each city', 'Official Tourist Guides'), ('no need', 'No staff needed'), ('other', 'Other')], default='staff', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='transportation_type',
            field=models.CharField(choices=[('', 'Select an option'), ('private bus', 'Private Bus'), ('public buses', 'Public Buses'), ('trains', 'Trains'), ('flights', 'Flights'), ('taxi', 'Taxi'), ('airport/station transfers', 'Airport/Station Transfers'), ('no transportation', 'No transportation'), ('other', 'Other')], default='transport', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='trip_duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='accommodations',
            field=models.CharField(choices=[('acc', 'Select accommodations type'), ('2-3 star hotels', '2-3 Star Hotels'), ('4-5 star hotels', '4-5 Star Hotels'), ('hostels with private bathroom', 'Hostels with private bathroom'), ('apartment', 'Apartment'), ('camping', 'Camping'), ('none', "None -  I'll take care of it"), ('other', 'Other')], default='acc', max_length=100),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='meals',
            field=models.CharField(blank=True, choices=[('meal', 'Select meals service'), ('breakfast only (BB)', 'Breakfast Only (BB)'), ('breakfast & dinner (HB)', 'Breakfast & Dinner (HB)'), ('breakfast, lunch & dinner (FB)', 'Breakfast, Lunch & Dinner (FB)'), ('no meals included', 'No meals included'), ('other', 'Other')], default='meal', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='staff',
            field=models.CharField(blank=True, choices=[('staff', 'Select staff service'), ('Tour leader during the entire trip', 'Tour leader during the entire trip'), ('Official tourist guides in each city', 'Official Tourist Guides'), ('no need', 'No staff needed'), ('other', 'Other')], default='staff', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='transportation_type',
            field=models.CharField(choices=[('', 'Select an option'), ('private bus', 'Private Bus'), ('public buses', 'Public Buses'), ('trains', 'Trains'), ('flights', 'Flights'), ('taxi', 'Taxi'), ('airport/station transfers', 'Airport/Station Transfers'), ('no transportation', 'No transportation'), ('other', 'Other')], default='transport', max_length=100),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='trip_duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
