# Generated by Django 5.1.2 on 2025-03-17 11:27

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0024_alter_historicaltriprequests_accommodations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='accommodations',
            field=models.CharField(choices=[('acc', 'Select accommodations type'), ('2-3 star hotels', '2-3 Star Hotels'), ('3-4 star hotels', '3-4 Star Hotels'), ('4-5 star hotels', '4-5 Star Hotels'), ('hostels with private bathroom', 'Hostels with private bathroom'), ('apartment', 'Apartment'), ('camping', 'Camping'), ('none', "None -  I'll take care of it"), ('other', 'Other')], default='acc', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='kind_of_group',
            field=models.CharField(blank=True, choices=[('group', 'Select type of group'), ('cultural_sightseeing', 'Cultural Group - Sightseeing'), ('schools_youth', 'Schools, Students or Youth'), ('backpackers', 'Backpackers'), ('theme_parks', 'Theme Parks (Eurodisney, Pinocchio, Mirabilandia, Puerto Aventura, Harry Potter...)'), ('study_language', 'Study or Language Package'), ('festivals_events', 'Festivals or Events'), ('sport', 'Sport'), ('family', 'Family'), ('religious', 'Religious'), ('relax_health_spas', 'Relax, Health, and SPAs'), ('adventure_nature', 'Adventure, Nature, Eco-tourism'), ('foodies_gastro_wine', 'Foodies - Gastro Tours - Wine Tours'), ('shopping', 'Shopping Tours'), ('yoga_meditation', 'Yoga or Meditation'), ('theme_tour', 'Theme Tour (Urban Art, Architecture, Science, Cinema...)'), ('photo_tours', 'Photo Tours'), ('cruises', 'Cruises'), ('vacation', 'Vacation')], default='group', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='transportation_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'Select an option'), ('private bus', 'Private Bus'), ('public buses', 'Public Buses'), ('trains', 'Trains'), ('flights', 'Flights'), ('taxi', 'Taxi'), ('airport/station transfers', 'Airport/Station Transfers'), ('no transportation', 'No transportation'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='accommodations',
            field=models.CharField(choices=[('acc', 'Select accommodations type'), ('2-3 star hotels', '2-3 Star Hotels'), ('3-4 star hotels', '3-4 Star Hotels'), ('4-5 star hotels', '4-5 Star Hotels'), ('hostels with private bathroom', 'Hostels with private bathroom'), ('apartment', 'Apartment'), ('camping', 'Camping'), ('none', "None -  I'll take care of it"), ('other', 'Other')], default='acc', max_length=100),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='kind_of_group',
            field=models.CharField(blank=True, choices=[('group', 'Select type of group'), ('cultural_sightseeing', 'Cultural Group - Sightseeing'), ('schools_youth', 'Schools, Students or Youth'), ('backpackers', 'Backpackers'), ('theme_parks', 'Theme Parks (Eurodisney, Pinocchio, Mirabilandia, Puerto Aventura, Harry Potter...)'), ('study_language', 'Study or Language Package'), ('festivals_events', 'Festivals or Events'), ('sport', 'Sport'), ('family', 'Family'), ('religious', 'Religious'), ('relax_health_spas', 'Relax, Health, and SPAs'), ('adventure_nature', 'Adventure, Nature, Eco-tourism'), ('foodies_gastro_wine', 'Foodies - Gastro Tours - Wine Tours'), ('shopping', 'Shopping Tours'), ('yoga_meditation', 'Yoga or Meditation'), ('theme_tour', 'Theme Tour (Urban Art, Architecture, Science, Cinema...)'), ('photo_tours', 'Photo Tours'), ('cruises', 'Cruises'), ('vacation', 'Vacation')], default='group', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='transportation_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'Select an option'), ('private bus', 'Private Bus'), ('public buses', 'Public Buses'), ('trains', 'Trains'), ('flights', 'Flights'), ('taxi', 'Taxi'), ('airport/station transfers', 'Airport/Station Transfers'), ('no transportation', 'No transportation'), ('other', 'Other')], max_length=100),
        ),
    ]
