# Generated by Django 5.1.2 on 2025-03-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0025_alter_historicaltriprequests_accommodations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
