# Generated by Django 5.1.2 on 2025-03-31 17:47

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0027_alter_historicaltriprequests_accommodations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='accommodations',
            field=models.CharField(choices=[('2-3 Star hotels', '2-3 Star Hotels'), ('3-4 Star hotels', '3-4 Star Hotels'), ('4-5 Star hotels', '4-5 Star Hotels'), ('Hostels with private bathroom', 'Hostels with private bathroom'), ('Apartment', 'Apartment'), ('Camping', 'Camping'), ('None', "None -  I'll take care of it"), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='currency',
            field=models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD'), ('mxn', 'MXN'), ('chf', 'CHF')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='kind_of_group',
            field=models.CharField(blank=True, choices=[('cultural_sightseeing', 'Cultural Group - Sightseeing'), ('schools_youth', 'Schools, Students or Youth'), ('backpackers', 'Backpackers'), ('theme_parks', 'Theme Parks (Eurodisney, Pinocchio, Mirabilandia, Puerto Aventura, Harry Potter...)'), ('study_language', 'Study or Language Package'), ('festivals_events', 'Festivals or Events'), ('sport', 'Sport'), ('family', 'Family'), ('religious', 'Religious'), ('relax_health_spas', 'Relax, Health, and SPAs'), ('adventure_nature', 'Adventure, Nature, Eco-tourism'), ('foodies_gastro_wine', 'Foodies - Gastro Tours - Wine Tours'), ('shopping', 'Shopping Tours'), ('yoga_meditation', 'Yoga or Meditation'), ('theme_tour', 'Theme Tour (Urban Art, Architecture, Science, Cinema...)'), ('photo_tours', 'Photo Tours'), ('cruises', 'Cruises'), ('vacation', 'Vacation')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='meals',
            field=models.CharField(blank=True, choices=[('Breakfast only (BB)', 'Breakfast only (BB)'), ('Breakfast & dinner (HB)', 'Breakfast & dinner (HB)'), ('Breakfast, lunch & dinner (FB)', 'Breakfast, lunch & dinner (FB)'), ('No meals included', 'No meals included'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='staff',
            field=models.CharField(blank=True, choices=[('Tour leader during the entire trip', 'Tour leader during the entire trip'), ('Official tourist guides in each city', 'Official Tourist Guides'), ('No need', 'No staff needed'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltriprequests',
            name='transportation_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Private bus', 'Private bus'), ('Public buses', 'Public buses'), ('Trains', 'Trains'), ('Flights', 'Flights'), ('Taxi', 'Taxi'), ('Airport/Station transfers', 'Airport/Station transfers'), ('No transportation', 'No transportation'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='accommodations',
            field=models.CharField(choices=[('2-3 Star hotels', '2-3 Star Hotels'), ('3-4 Star hotels', '3-4 Star Hotels'), ('4-5 Star hotels', '4-5 Star Hotels'), ('Hostels with private bathroom', 'Hostels with private bathroom'), ('Apartment', 'Apartment'), ('Camping', 'Camping'), ('None', "None -  I'll take care of it"), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='currency',
            field=models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD'), ('mxn', 'MXN'), ('chf', 'CHF')], max_length=20),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='kind_of_group',
            field=models.CharField(blank=True, choices=[('cultural_sightseeing', 'Cultural Group - Sightseeing'), ('schools_youth', 'Schools, Students or Youth'), ('backpackers', 'Backpackers'), ('theme_parks', 'Theme Parks (Eurodisney, Pinocchio, Mirabilandia, Puerto Aventura, Harry Potter...)'), ('study_language', 'Study or Language Package'), ('festivals_events', 'Festivals or Events'), ('sport', 'Sport'), ('family', 'Family'), ('religious', 'Religious'), ('relax_health_spas', 'Relax, Health, and SPAs'), ('adventure_nature', 'Adventure, Nature, Eco-tourism'), ('foodies_gastro_wine', 'Foodies - Gastro Tours - Wine Tours'), ('shopping', 'Shopping Tours'), ('yoga_meditation', 'Yoga or Meditation'), ('theme_tour', 'Theme Tour (Urban Art, Architecture, Science, Cinema...)'), ('photo_tours', 'Photo Tours'), ('cruises', 'Cruises'), ('vacation', 'Vacation')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='meals',
            field=models.CharField(blank=True, choices=[('Breakfast only (BB)', 'Breakfast only (BB)'), ('Breakfast & dinner (HB)', 'Breakfast & dinner (HB)'), ('Breakfast, lunch & dinner (FB)', 'Breakfast, lunch & dinner (FB)'), ('No meals included', 'No meals included'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='staff',
            field=models.CharField(blank=True, choices=[('Tour leader during the entire trip', 'Tour leader during the entire trip'), ('Official tourist guides in each city', 'Official Tourist Guides'), ('No need', 'No staff needed'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triprequests',
            name='transportation_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Private bus', 'Private bus'), ('Public buses', 'Public buses'), ('Trains', 'Trains'), ('Flights', 'Flights'), ('Taxi', 'Taxi'), ('Airport/Station transfers', 'Airport/Station transfers'), ('No transportation', 'No transportation'), ('Other', 'Other')], max_length=100),
        ),
    ]
